name: release farskapsportal-api
on:
  push:
    branches:
      - release
    paths:
      - 'pom.xml'
      - 'apps/api/**'
      - 'libs/**'
      - '.nais/apps/api/**'
      - '**/api-ci.yml'

env:
  GITHUB_USERNAME: x-access-token
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  verify:
    name: Verify that release commit is present in main branch
    runs-on: ubuntu-latest

    steps:
      - run: git clone --bare https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/${{ github.repository }}
      - name: check if commit to build exists in main branch
        run: |
          cd $( echo ${{ github.repository }} | sed 's;navikt/;;' ).git
          git log | grep -c ${{ github.sha }}
  build:

    permissions:
      contents: "read"
      id-token: "write"
    name: Build release with maven and docker
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-java@v3
        if: env.NOT_FOUND == 'true'
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn -B --no-transfer-progress package --settings .m2/maven-settings.xml --file pom.xml
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: farskapsportal
          image_suffix: api
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    outputs:
      image: ${{ steps.docker-push.outputs.image }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy docker image to prod
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          path: deploy
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: deploy/.nais/apps/api/naiserator-prod.yml
          VARS: deploy/.nais/apps/api/prod.yml
          IMAGE: ${{ needs.build.outputs.image }}

