name: continuous integration asynkron
on:
  push:
    branches:
      - '**'
      - '!release'
    paths:
      - 'pom.xml'
      - 'apps/asynkron/**'
      - 'libs/**'
      - '.nais/apps/asynkron/**'
      - '**/asynkron-ci.yml'

env:
  GITHUB_USERNAME: x-access-token
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  build:
    permissions:
      contents: "read"
      id-token: "write"
    name: Build with maven and docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-java@v3
        if: env.NOT_FOUND == 'true'
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - uses: actions/cache@v3
        if: env.NOT_FOUND == 'true'
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn install -B -e
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: farskapsportal
          image_suffix: asynk
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    outputs:
      image: ${{ steps.docker-push.outputs.image }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy docker image to dev
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          path: deploy
      - name: Deploy main to dev-gcp
        if: github.ref == 'refs/heads/main'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/.nais/apps/asynkron/naiserator-dev.yml
          VARS: deploy/.nais/apps/asynkron/main.yml
          IMAGE: ${{ needs.build.outputs.image }}
      - name: Deploy feature to dev-gcp
        if: github.ref != 'refs/heads/main'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/.nais/apps/asynkron/naiserator-dev.yml
          VARS: deploy/.nais/apps/asynkron/feature.yml
          IMAGE: ${{ needs.build.outputs.image }}
